### ISSUE TITLE
window生成

### ISSUE THREAD

**Issue by OkamotoKazuma** [human-osaka-game-2019/BLOCKBREAK#2]
- フルスクリーンでの生成

**Comment by taishi-matsumura** [comment]
フルスクリーンモードだとデバッグしにくかったりして作業が進まなくなると思うので、ある程度動くようになるまではウィンドウモードで作れば良いと思います。
そこから「そろそろフルスクの機能入れよっか」ぐらいのノリで着手すれば良いかと。
その場合も、ウィンドウモードとフルスクリーンモードを簡単に切り替えられるようにしておいた方が良いでしょうね。(その辺りは着手してから考えましょう)
